Chernykh Sergey pull request
dvm-system/tsar pull request #2
Opened 2019-12-11 20:27 UTC by SergeyChernykh

2019-12-12 13:07 UTC, kaniandr requested changes
Посмотрел файлы связанные с выделением вызовов в отдельные базовые блоки.

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +// This file implements passe to do split basik block on call instr.
```suggestion
// This file implements a pass to extract each call instruction (except debug instructions) into its own new basic block.
```

2019-12-12 13:07 UTC, kaniandr commented on include/tsar/Transform/IR/SplitBasicBlocksWithCallInst.h
> +//===--- SplitBasicBlocksWithCallInst.h ---  Split Basic Block Tranform ----------*- C++ -*-===//
Т.к. данный проход выполняет преобразования и не должен быть запрошен через getAnalysis<...>, нужно удалить заголовочный файл, а объявление прохода перенести в .cpp файл в безымянное пространство имен `namespace {}`. Таким образом единственным способом создать проход будет вызов соответствующей функции `create...`.

2019-12-12 13:07 UTC, kaniandr commented on include/tsar/Transform/IR/Passes.h
> +FunctionPass* createSplitBasicBlocksWithCallInstPass();
Добавить комментарий по аналогии с другими функциями.

2019-12-12 13:07 UTC, kaniandr commented on include/tsar/Transform/IR/Passes.h
> +void initializeSplitBasicBlocksWithCallInstPassPass(PassRegistry& Registry);
Должна быть вызвана в `initializeIRTransform()` в  lib/tsar/Transform/IR/Passes.cpp, чтобы обеспечить инициализацию прохода при запуске анализатора.

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +// Copyright 2018 DVM System Group
Год заменить на 2019

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +#include <tsar/Transform/IR/SplitBasicBlocksWithCallInst.h>
`#include` должны быть отсортированы в лексикографическом порядке (см. раздел Заголовочные файлы в [руководстве разработчика](https://github.com/dvm-system/tsar/wiki/Coding-Standards)).

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +INITIALIZE_PASS_BEGIN(SplitBasicBlocksWithCallInstPass, "Split-BB",
Предлагаю переименовать проход, функции его создания и инициализации, макрос `DEBUG_TYPE` и соответствующий файл.
Файл и проход (а также производные имена функций) `CallExtractor`.
Короткое название прохода и макрос 'extract-call'.
Полное название `"Extract calls into new basic block"`.

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +    "Split BB in call instraction", false, true)
Это не проход анализа.
```suggestion
    "Split BB in call instraction", false, false)
```

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +  "Split BB in call instraction", false, true)
Это не проход анализа.
```suggestion
  "Split BB in call instraction", false, false)
```

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +void SplitBasicBlocksWithCallInstPass::getAnalysisUsage(AnalysisUsage & AU) const {
Если метод не нужно, он должен быть убран из объявления класса и отсюда.
```suggestion
```

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +}
```suggestion
```

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +  LLVM_DEBUG(
Одно более короткое сообщение вместо двух.
`"[EXTRACT CALL]: Start processing of the function " << F.getName() << "\n"`

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +      TerminatorInst* ti = currBB->getTerminator();
Именование, все переменные - с большой буквы.

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +
Пустые строки, только если они действительно нужны и облегчают восприятие.
```suggestion
```

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +            if (i != ti) {
Уже ведь есть проверка выше, разве это не всегда выполняется здесь?

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +              else {
`else` на той же строке, что и предыдущая `}`, т.е. `} else {`.
Либо, что в данном случае будет лучше, т.к. обе ветки содержат один оператор вообще без `{}` в обоих ветках.

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +        if (ti != nullptr ) {
`ti` ведь нигде не обновляется, можно видимо вынести проверку перед циклом, и не проверять на каждой итерации, если терминальная инструкция нулевая, то сразу переходить к следующему блоку?

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +              currBB++;
Вы уверены, что в случае когда вызов - первая инструкция, этот сдвиг необходимо, не пропустите ли вы следующий вызов, если их было два в блоке?
сurrBB->[сall...], после разбиения currBB->[call] [...], после ++ [call] currBB->[...], так ?

2019-12-12 13:07 UTC, kaniandr commented on lib/Transform/IR/SplitBasicBlocksWithCallInst.cpp
> +}
Добавьте завершающую пустую строку.
```suggestion
}

```

2019-12-12 19:33 UTC, SergeyChernykh commented
Исправил Ваши замечания и немного оптимизировал функцию.

2019-12-12 20:22 UTC, kaniandr requested changes
Мелкие правки по оформлению кода.

2019-12-12 20:22 UTC, kaniandr commented on include/tsar/Transform/IR/Passes.h
> +/// Create a pass which extract each call instruction (except debug instructions) into its own new basic block.
Длина строк не больше 80 символов.

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +//===--- SplitBasicBlocksWithCallInst.cpp --- Split Basic Block Tranform ----------*- C++ -*-===//
Имя файла и заголовок Extract each call into a new block, текущий слишком общий (длина строки не более 80 символов).

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +    F.dump();
Чтобы вывести функцию до преобразования (и после) есть специальные опции командной строки.
-print-before-all, -print-after-all - выведет для всех проходов преобразования
-print-before=<name>, -print-after=<name> - для прохода <name>
Поэтому ручная выдача избыточна, кроме того, если LLVM  в релизе, а TSAR в дебаге, код не слинкуется без макроса `TSAR_LLVM_DUMP`.
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +    dbgs() << "[EXTRACT CALL]: Befor transformation:\n";
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +  if (F.hasName() && !F.empty()) {
Зачем проверка `F.hasName()`?

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +    dbgs() << "[EXTRACT CALL]: " << F.getName()
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +    << " After transformation:\n";
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +    F.dump();
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +      }
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +      else {
```suggestion
      } else {
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +      CurrBB != LastBB; ++CurrBB) {
```suggestion
         CurrBB != LastBB; ++CurrBB) {
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +        for (Instruction* i = &*(++CurrInstr); i != TermInst;
`i` -> `I`

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +          ++CurrInstr, i = &*CurrInstr) {
```suggestion
             ++CurrInstr, i = &*CurrInstr) {
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +    << "Start processing of the function \n" << F.getName();
```suggestion
      << "start processing of the function " << F.getName() << "\n";
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +      << "End processing of the function \n" << F.getName();
```suggestion
      << "end processing of the function " << F.getName() << "\n"; 
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +INITIALIZE_PASS_BEGIN(CallExtractorPass, "extract-call",
```suggestion
INITIALIZE_PASS_(CallExtractorPass, "extract-call",
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +INITIALIZE_PASS_END(CallExtractorPass, "extract-call",
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +  "Extract calls into new basic block", false, false)
```suggestion
```

2019-12-12 20:22 UTC, kaniandr commented on lib/Transform/IR/CallExtractor.cpp
> +  class CallExtractorPass : public FunctionPass, private bcl::Uncopyable {
`namespace` не добавляет отступов (см. раздел Отступы https://github.com/dvm-system/tsar/wiki/Coding-Standards)

2020-05-24 18:24 UTC, closed without merging

2020-05-24 18:25 UTC, kaniandr commented
Окончательная версия была добавлена в проект в #4 .