[TSAR] Add pointer reduction pass
dvm-system/tsar pull request #5
Opened 2020-02-27 21:28 UTC by v-makeev

2020-05-24 18:17 UTC, kaniandr reviewed
Я добавил пояснения и вопросы к коду.
Общее дополнение, надо перенести файлы из `Analysis/Memory` в `Transform/IR`, т.к. ваш проход относится к преобразованиям кода.

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +      }
Что делает этот код, разве `Value` уже не содержит аргументы `load`?

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +      return !L->contains(to) && hasPathInCFG(from, to, visited);
1. Странная проверка, почему здесь `return`? Вы находите первую инструкцию вызова и если для нее проверка выполнена возвращаете `true`, а если для других инструкций проверка не выполнена?
2. В чем смысл проверки hatPathInCFG() ? Эта проверка запрещает преобразования в следующем коде.
```C++
void bar(int *);

int foo(int N) {
  int S;
  bar(&S);
  for (int I = 0; I < N; ++I)
    S = S * I;
  return S;
}
```

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +    insertDbgValueCall(store, ctx.F, ctx.L, insertBefore->getDebugLoc(), insertBefore);
Зачем вставляется `dbg.value` для `store`? Инструкцию `dbg.value` можно привязать только к регистру, у `store` нет возвращаемого значения, т.е. эта инструкция привязывается в пустоту, в LLVM IR будет `badref`:
```llvm
 call void @llvm.dbg.value(metadata void <badref>, metadata !43, metadata !DIExpression()), !dbg !50
```

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +  Inst->setMetadata("sapfor.dbg", debug);
Переменная, которая указывается в `dbg.value` должна быть та, что была указана в `dbg.declare` для заменяемой переменной. Не нужно здесь создавать новую переменную, иначе анализатор не сможет связать эту новую переменную со старой. Для связывания используется отладочная информация (`DIVariable`), если она разная, то переменные разные. В дерево псевдонимов эти новые переменные попадают, но свойства для цикла по ним добавлены не будут, если они не существовали в исходном коде до вызова SROA, т.е. если для них не было `dbg.declare`, которые используются для первого построения дерева псевдонимов.

Будет __проблема__ с глобальными переменными, т.к. в `dbg.value` должна быть `DILocalVariable`. Давайте для них будем создавать новые DILocalVariable с тем же именем и флагом `DINode::FlagArtificial`, а также пометим их через `sapfor.da`. Тогда потом, я добавлю соответствующую проверку в анализ зависимостей, чтобы свойства обновлялись и для глобальных переменных тоже.

Кроме того `dbg.value` для той переменной, которая раньше перезаписывалась в `store`, т.е. если там было `S = ...`, то к регистру который раньше сохранялся в `store` на месте этого `store` нужно поставить `dbg.value`.
Также к этому `dbg.value` нужно указать `!dbg`, который указывал позицию в исходном коде для замененного `store`.

```llvm
for.body:                                         ; preds = %for.cond
  %3 = load i32, i32* %S, align 4, !dbg !48, !tbaa !42
  %mul = mul nsw i32 %3, %I.0, !dbg !49
  store i32 %mul, i32* %S, align 4, !dbg !50, !tbaa !42
  %inc = add nsw i32 %I.0, 1, !dbg !51
  call void @llvm.dbg.value(metadata i32 %inc, metadata !15, metadata !DIExpression()), !dbg !34
  br label %for.cond, !dbg !52, !llvm.loop !53
```
должно превратится в
```llvm
  %mul = mul nsw i32 %phi.for.cond, %I.0, !dbg !51
  call void @llvm.dbg.value(metadata i32 %mul, metadata !14, metadata !DIExpression()), !dbg !50
  %inc = add nsw i32 %I.0, 1, !dbg !52
  call void @llvm.dbg.value(metadata i32 %inc, metadata !15, metadata !DIExpression()), !dbg !34
  br label %for.cond, !dbg !53, !llvm.loop !54
```
Сейчас для `%mul` метаданные не добавляются.

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +    SmallDenseSet<Value *> Values;
В `Values` попадают все возможные кандидаты на размещения на регистрах? И потом они все вместе обрабатываются, т.е. если одну из переменных разместить нельзя, то не будет обработаны все?

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +                  if (L->contains(LI) && hasPossibleReductionUses(LI)) {
`hasPossibleReductionUses()` стоит убрать, т.к. на самом деле это преобразование должно быть полезно не только для редукции, но и для анализа приватных переменных. Для них я добавил дополнительный анализ, если они были размещены на регистрах. Так что стоит пытаться преобразовать всегда, если найдены зависимости.

2020-05-24 18:17 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +              for (auto *User : V->users()) {
А что сейчас заменяется, только `alloca` и глобальные переменные, или что-то еще?

2020-05-26 01:16 UTC, v-makeev commented on lib/Analysis/Memory/PointerReduction.cpp
> +      }
Переменная может не прокинуться на регистры (если брали ссылку от указателя, например) и там будет два load подряд. Я пытаюсь сделать преобразование и для таких случаев тоже, вынося два load'а перед циклом

2020-05-26 01:20 UTC, v-makeev commented on lib/Analysis/Memory/PointerReduction.cpp
> +      return !L->contains(to) && hasPathInCFG(from, to, visited);
1. Поправил на возврат только если false
2. Разрешает, например, в таком, поэтому проверяю, что функция от указателя выполняется после цикла
```C
int *x;
void f(int *a) { x = a; }
void g() {*x = 0; }

int foo(int N) {
  int S;
  f(&S);
  for (int I = 0; I < N; ++I) {
    S = S * I;
    g();
  }
  return S;
}
```

2020-05-26 01:20 UTC, v-makeev commented on lib/Analysis/Memory/PointerReduction.cpp
> +    insertDbgValueCall(store, ctx.F, ctx.L, insertBefore->getDebugLoc(), insertBefore);
Убрал

2020-05-26 01:24 UTC, v-makeev commented on lib/Analysis/Memory/PointerReduction.cpp
> +    SmallDenseSet<Value *> Values;
В `Values` все переменные, для которых есть load, так что по идее все. В цикле должно быть `continue`, поправил

2020-05-26 01:24 UTC, v-makeev commented on lib/Analysis/Memory/PointerReduction.cpp
> +              for (auto *User : V->users()) {
Да, только они

2020-05-26 07:50 UTC, kaniandr commented on lib/Analysis/Memory/PointerReduction.cpp
> +      return !L->contains(to) && hasPathInCFG(from, to, visited);
То что `g()` косвенно меняет `S` можно проверить по дереву псевдонимов, а если `g()` нет, то `f()` может просто инициализировать начальное значение, и преобразование будет допустимо.

2020-11-07 10:39 UTC, kaniandr requested changes
Нужно обновиться до послдней версии master.

2020-11-07 10:39 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +      Inst.getAllMetadata(MDs);
Так получить связанные с инструкцией MDNode из дерева псевдонимов не получится. getAllMetadata() возвращает только явно привязанные MDNode, например !dbg .... Вершины дерева к инструкциям так не привязаны. Для этих целей есть набор методов `getRawDIMemoryIfExists(...)` в https://github.com/dvm-system/tsar/blob/3ac4e77a0b00e059237514a42884b756b94ab228/include/tsar/Analysis/Memory/DIEstimateMemory.h#L479

Т.е. 
```C++
 if (DIMTraitItr == Pool.end()) {
          continue;        
```
всегда будет срабатывать и проверка не будет выполняться.

Но в данном случае я думаю обходить все инструкции - лишнее, у вас уже есть Pool и в нем есть вся память, что используется в цикле. Нет необходимости обходить все инструкции заново, достаточно обойти память в Pool и для нее проверять достижимость с текущей памятью, не забыва, конечно, что сама проверяемая память тоже по идее есть в Pool.

2020-11-07 10:39 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +        if (L->contains(I)) {
Подозреваю, что этого не достаточно, нужно чтобы и использования `I` не использовались внутри цикла, иначе в цикле будет доступ к значению переменной разными способами.

И еще, в LLVM есть `Instruction` и есть `ConstantExpr`, последнее может использоваться внутри инструкции, что-то в духе `call foo(getelementptr ...)`, т.е. GEP будет прямо внутри вызова вычисляться, а не как отдельная инструкция. Интерфейс у них похожий и также можно проверить использования для выражений. Вообще для удоства работы в LLVM есть обертка `llvm::Operator`, к нему приводятся и инструкции, и выражения через `llvm::dyn_cast`. Это я к том, что здесь стоит и для выражений делать проверку.

2021-03-20 16:03 UTC, kaniandr reviewed
- Тесты надо перенести в репозиторий с тестами в соответствующем формате. Можно сделать в него pull request.
- Нужно поправить форматирование (именование переменных (с заглавной буквы), длина строк).


Думаю полезные рекомендации:
- https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements
- https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

2021-03-20 16:03 UTC, kaniandr commented on include/tsar/Analysis/Memory/Passes.h
> +FunctionPass *createPointerReductionPass();
```suggestion
```

2021-03-20 16:03 UTC, kaniandr commented on include/tsar/Transform/IR/Passes.h
> +FunctionPass *createPointerReductionPass();
Нужно добавить комментарий с описанием прохода.

2021-03-20 16:03 UTC, kaniandr commented on include/tsar/Transform/IR/PointerReduction.h
> +#include "Passes.h"
- Стоит перенести объявление класса в `.cpp` файл в безымянный `namespace`, т.к. это проход преобразования, он не может быть запрошен в качестве результата анализа и должен создаваться и добавляться в менеджер проходов явно, через `create...`.
- В начале всех добавляемых файлов с исходным кодом должна быть стандартная шапка с описанием файла и лицензионным соглашением.

2021-03-20 16:03 UTC, kaniandr commented on include/tsar/Transform/IR/PointerReduction.h
> +class PointerReductionPass : public FunctionPass, private bcl::Uncopyable {
Я бы переименовал проход и файлы, в которых он объявлен:
- проход выполняет преобразование, а не анализ;
- преобразование формально не связано с редукцией, более того он может быть полезно и для других анализов (индуктивные и приватные переменные).

Лучше, если название будет явно отражать то, что делает проход.

2021-03-20 16:03 UTC, kaniandr commented on include/tsar/Transform/IR/PointerReduction.h
> +  void releaseMemory() override { }
```suggestion
```

2021-03-20 16:03 UTC, kaniandr commented on include/tsar/Transform/IR/PointerReduction.h
> +  /// Executes reach definition analysis for a specified function.
```suggestion
```

2021-03-20 16:03 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +  // 1. Find memory that was marked anti after the first step;
Ведь речь не только про `anti`, либо комментарий должен соответствовать коду, либо можно его просто убрать совсем.

2021-03-20 16:03 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +  // 5. Check if this helped; TODO
О чем этот пункт?

2021-03-20 16:03 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +                if (hasLoopLoad && hasLoopStore) {
Требование и `load` и `store` вызвано только тем, что проход изначально был направлен на редукцию?
Вроде бы нет причин, не делать преобразование, если есть только какой-то один вид обращений?

2021-03-20 16:04 UTC, kaniandr commented on include/tsar/Transform/IR/PointerReduction.h
> +class PointerReductionPass : public FunctionPass, private bcl::Uncopyable {
Я пока только начал смотреть...

2021-03-21 12:26 UTC, kaniandr reviewed
Посмотрел проверки на допустимость преобразования.

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +      Pool = std::make_unique<DIMemoryTraitRegionPool>();
Зачем? Почему просто не перейти к другому циклу?

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    auto &Pool = TraitPool[L->getLoopID()];
`getLoopID()` может вернуть `nullptr` для некоторых циклов.

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    DenseSet<Value *> toDelete;
Кажется, что это не очень большое множество, может использовать `llvm::SmallPtrSet` ?

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +        T.unset<trait::NoPromotedScalar>();
Не слишком ли рано снимается свойство, ведь проверок еще не было, а если преобразование не будет выполнено?

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    }
Что делает эта проверка?

```C++
int *X;
for (int I = 0; I < 10; ++I) {
  *X *= I;
}
```
В IR будет что-то такое:

`load` из `alloca` -> `%1`
`load` из `%1` -> значение `X`

В `Values` будут `alloca` и `load alloca`, а после проверки останется только `load alloca`? 
Получается здесь попытка пробросить самое последнее разыменование? Зачем? Довольно мала вероятность, что при наличии многоуровневых `load` анализатор поймет какие из этих `load` в самом низу ведут к одной и той же памяти, т.е. почти всегда будет диагностирован косвенный доступ, что должно запретить преобразование. Или это не так?

Дальше мне тоже не понятно, в цикле по `Values`, если встречается `load`, то берется то, из чего грузится? Т.е. в таком примере должно было быть `alloca`. Получается мы сначала выбросили `alloca` из списка, а потом взяли его из `load`?

Что я упускаю?

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +bool validateValue(PtrRedContext &Ctx) {
```suggestion
bool validateValue(const PtrRedContext &Ctx) {
```

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +      DenseSet<BasicBlock *> visited;
```suggestion
```

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +      if (Ctx.L->contains(Call->getParent()) && Call->getParent() != Ctx.L->getExitingBlock()) {
- Почему допустим вызов из `ExitingBlock`?
- Может быть несколько `ExitingBlock`-ов, тогда `getExitingBlock()` вернет `nullptr`.

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    if (Ctx.ValueChanged && Store && Ctx.L->contains(Store)) {
Что отсекает эта проверка?

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    if (Call) {
Нужна ли вообще эта проверка?
Если по адресу будет обращение внутри вызова, то это отловит проверка по дереву псевдонимов.
А если это просто использование адреса без разыменования, вроде бы ничего плохого в этом нет, ведь после цикла адрес останется валидным, даже если внутри вызова он куда будет сохранен.

Мне кажется эти же рассуждения справедливы и для GEP.

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    if (auto *SI = dyn_cast<LoadInst>(User)) {
А почему только `load`? Ведь убираются и `load` и `store`, а `volatile` инструкции по идее вообще нельзя трогать.

2021-03-21 12:26 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +  auto *EM = AT.find(MemoryLocation(V));
Это не совсем правильный поиск. `find()` ищет участок памяти, покрывающий заданный, т.к. размер не указан, то он будет принят как `unknown`, а `unknown` трактуется как самый большой размер. Но, если анализатор знает точный максимально возможный размер, то участка памяти с `unknown` размером не будет в дереве и `find()` ничего не найдет.

Правильнее было бы искать самый маленький объект (например с размером 1 или даже 0), а потом для результата взять top-level parent. При этом любой используемый участок памяти должен быть в дереве, если его там нет, велика вероятность ошибки (либо при вызове поиска, либо при построении дерева), поэтому для результата `find()` возможно даже стоит поставить `assert()` (в том числе и ниже, где поиск для `Loc`).

2021-03-25 22:44 UTC, v-makeev commented on include/tsar/Transform/IR/PointerReduction.h
> +class PointerReductionPass : public FunctionPass, private bcl::Uncopyable {
Переименовал в PointerScalarizer, надеюсь, так звучит лучше

2021-03-25 22:45 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +  // 1. Find memory that was marked anti after the first step;
Комментарий писал еще зимой прошлого года, обновил его

2021-03-25 22:45 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +  // 5. Check if this helped; TODO
Убрал

2021-03-25 22:46 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +      Pool = std::make_unique<DIMemoryTraitRegionPool>();
Сделал вместо этой строки `return`

2021-03-28 11:55 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +      if (Ctx.L->contains(Call->getParent()) && Call->getParent() != Ctx.L->getExitingBlock()) {
Вызов допустим, потому что инструкции `store`, которые загружают значение назад, вставляются в начало `ExitBlock`-ов. То есть этот `call` уже никак не мешает преобразованию, и там указатель может спокойно меняться

2021-03-28 12:07 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +    if (Ctx.ValueChanged && Store && Ctx.L->contains(Store)) {
ValueChanged это флаг, который по сути ставится для двойных указателей (когда load делается 2 раза поряд, чтобы получить значение переменной). Я пытаюсь для таких указателей выносить 2 `load`-а из цикла, и далее делать все аналогично обычному преобразованию. Эта проверка отсекает случай, когда в цикле есть как инструкции вида `*X = ...`, так и инструкции с использованием `**X`

2021-03-28 12:32 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +    }
Тут я пытался гарантированно избавиться от лишних `Value`, но получилось не очень.
Если рассмотреть тот же пример выше, но сделать X глобальным, то в IR (после SROA) будет:
* `load` из `%1` -> `%2` (значение `*X`)
* `load` из `%2` -> значение `X`
При этом в `Values` попадут как `%1`, так и `%2` (они оба участвую в load). Но они по сути связаны с одной переменной и рассматривать их оба будет неправильно. Поэтому я пытался оставить только самые нижние `load`, а потом подняться по ним к самой `Value`. Переделаю наоборот: буду брать самые верхние инструкции по цепочке `load`-ов

2021-03-29 22:05 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +                if (hasLoopLoad && hasLoopStore) {
Да, оказалось, что у меня неправильно обрабатывались некоторые store (например, `store 3, x`, т.е. когда аргумент не `llvm::Instruction`). Поправил это и убрал проверку на `Load`. Возможно на `Store` тоже стоит, но мне кажется, будет попадать слишком много лишних переменных

2021-03-29 22:05 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +        T.unset<trait::NoPromotedScalar>();
Передвинул

2021-03-29 22:06 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +    if (Call) {
Была ошибка в проверке по дереву псевдонимов, доделал ее и убрал проверки на GEP и Call

2021-04-17 12:28 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +//===- PointerScalarizer.cpp - Promoting certain values after SROA  --------- *- C++ -*-===//
```suggestion
//=== PointerScalarizer.cpp - Promoting certain values after SROA * C++ *-===//
```

2021-04-17 12:28 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +// Copyright 2018 DVM System Group
```suggestion
// Copyright 2021 DVM System Group
```

2021-04-17 12:28 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        T.unset<trait::NoPromotedScalar>();
Получается свойство снимается для участков памяти, хотя проброшена была только часть из них?

2021-04-17 12:28 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  };
```suggestion
};
```

2021-04-17 12:28 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +bool validateValue(const ScalarizerContext &Ctx) {
```suggestion
static inline bool validateValue(const ScalarizerContext &Ctx) {
```

2021-04-17 12:28 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +    if (Ctx.ValueChanged && Store && Ctx.L->contains(Store)) {
`store` может делаться как в X, так и самом значение может куда-то сохраняться.

Такой случай не допустим, и видимо он и проверяется?
```C++
int *X;
for (....) {
  X= ...
  ... *X  ...;
}
```

Такой случай вроде бы допустим.
```C++
int *X;
for (....) {
  int Y = X;
  ... *X  ...;
}
```

Наверное, нужна проверка каким операндом у `store` является `X`.

PS: **X - это уже 3 `load`, если это `alloca` или глобальная переменная и 2 если это аргумент функции, `alloca` для которого была проброшена:

```llvm
@X = dso_local global i32** null, align 8, !dbg !0

%0 = load i32**, i32*** @X, align 8, !dbg !18, !tbaa !19
%1 = load i32*, i32** %0, align 8, !dbg !23, !tbaa !19
%2 = load i32, i32* %1, align 4, !dbg !24, !tbaa !25

```

2021-04-17 12:43 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +        T.unset<trait::NoPromotedScalar>();
Получается свойство снимается для всех участков памяти, хотя проброшена была только часть из них?

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        continue;
`ExitBlock` - это блок вне цикла, а `for` делается по инструкциям в цикле. Т.е. эта проверка никогда не сработает, `InExit` - всегда `false`.

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        return false;
Может быть вынести проверку в самый первый цикл в `runOnFunction`, где формируется множество `Values`?

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        auto *EMNode = EM->getAliasNode(AT);
Лучше вынести вычисление EMNode из лямбды. Это не очень дорогая операция, но все-таки это не просто `return  ` известного значения.

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        if (!STR.isEqual(EMNode, InstNode) && !STR.isUnreachable(EMNode, InstNode))
`isEqual` - тоже не безопасно, т.к. два участка памяти могут попасть в общую `AliasNode` и при этом быть порождены разными переменными. Два указателя `X` и `Y` указывающие на одну память, вполне могут быть в одной `AliasNode` и `isEqual` вернет `true`.

Кажется, что самое безопасное это разрешать только:
`InstEM->getTopLevelParent() == EM`

Вообще странно, что не проверяется, что это за инструкция. Ведь проход заменяет только `load` и `store`, а если это будет что-то другое, пусть даже с явным указанием переменной, замена выполнена не будет.

__Более того, мне кажется, проверка должна быть еще жестче.__ Нужно, чтобы если была найден `store` или `load` использующий `EM`, то делать это он должен обязательно через `V`. Чтобы (a) избежать обращений к части того, на что указывает `V`, например, если будет приведение типов, (b) чтобы избежать обращений через синонимичные конструкции, например a[5] - это `getelementptr`, в разных участках функции может быть несколько инструкций `getelementptr` вычисляющих этот адрес (адрес один - инструкций несколько), в EM будет только одна из них (какая-то), а в цикле может быть другая, т.е. часть инструкций может не быть обработана.

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      }
А почему просто не использовать `findMetadata()`?

Еще есть метод `llvm::findDbgUsers`, можно любо просто им воспользоваться, либо взять реализацию из него, она эффективнее, чем просто перебор всех инструкций, т.к. для MDNode тоже есть `def-use` цепочки и можно просто получить список всех `use` для объекта.

```C++
void llvm::findDbgUsers(SmallVectorImpl<DbgVariableIntrinsic *> &DbgUsers,
                        Value *V) {
  // This function is hot. Check whether the value has any metadata to avoid a
  // DenseMap lookup.
  if (!V->isUsedByMetadata())
    return;
  if (auto *L = LocalAsMetadata::getIfExists(V))
    if (auto *MDV = MetadataAsValue::getIfExists(V->getContext(), L))
      for (User *U : MDV->users())
        if (DbgVariableIntrinsic *DII = dyn_cast<DbgVariableIntrinsic>(U))
          DbgUsers.push_back(DII);
}
```
Единственное ограничение этого метода, он не будет работать, если `V` - `Constant`.  Соответствующая реализация есть в `tsar/Analysis/Memory/Utils.cpp`, она правда `static`. Но мне кажется константы все равно здесь не обрабатываются, так что она не нужна. Может быть нужна проверка, чтобы ничего не упало. У `findMetadata` таких проблем нет.

И нет проверки DIExpression, а если там не пусто - это не вызовет проблем?

Вообще с одной `Value` может быть связано несколько `dbg.value`, например, если в исходном коде было `X=Y`, то фактически присваивания в IR может уже не быть, если `X` и `Y` были проброшены. Вместо него будет две `dbg.value`, связывающие регистр с `X` и `Y`. Т.е. после преобразования вторая потеряется?

Кроме того кажется важным, чтобы эти `dbg.value` были вне цикла, т.к. их наличие будет означать наличие `X=Y` в исходном коде. Такие `dbg.value` символизирующие присваивания используются на более поздних этапах анализа и нельзя, чтобы они исчезли. Про `dbg.declare` это не так страшно, они по идее почти всегда в начале функции, но для аккуратности для них тоже стоит проверять.

Также один регистр может означать разные переменные в разных точках программы, т.е. в одной точке `Value` может быть и `X` и `Y`, а в другой, например, только `X`. Т.е. мы должны знать, что если это метаданные заданы через `dbg.value`, то в рамках цикла нет других метаданных, связывающих наш регистр с какими-то новыми переменными.

```C++
void foo(int *X) {
  int *Y;
  *X = 5;
  Y = X;
  *Y = 4;
}
```

После SROA будет

```llvm
define dso_local void @foo(i32* %X) #0 !dbg !8 {
entry:
  call void @llvm.dbg.value(metadata i32* %X, metadata !15, metadata !DIExpression()), !dbg !17
  store i32 5, i32* %X, align 4, !dbg !18, !tbaa !19
  call void @llvm.dbg.value(metadata i32* %X, metadata !16, metadata !DIExpression()), !dbg !17
  store i32 4, i32* %X, align 4, !dbg !23, !tbaa !19
  ret void, !dbg !24
}
```

Есть разновидность метода `findMetadata`, у которой второй параметр - `Users`. Она найдет только те переменные, которые связаны с этим регистром в точках использования. `Users` - формально может быть любая инструкция, не обязательно точка явного использования. Например, если это будет первая инструкция в голове цикла, то т.к. голов доминирует все инструкции в теле цикла, то если будет гарантировано, что других `dbg.value` в цикле нет для нашего регистра, то этот метод вернет список всех переменных, которые привязаны к регистру на входе в цикле и значит и внутри цикла.

Т.е. если обрабатывать случаи, когда пробрасывается не `alloca`, а, например, параметр-указатель функции, который был проброшен в SROA. То нужно проверить отсутствие для него `dbg.value` внутри тела цикла, а в качестве связанных переменных брать то, что вернет `findMetadata` в начале итерации цикла.

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      AT.getDomTree());
Меня смущает этот поиск.
Сначала был найден `EM` того размера, с которым идет работа (причем если добавить проверки, про которые я писал в комментариях к `analyzeAliasTree` других обращений (к части или к большей памяти) в цикле быть не должно). А теперь выполняется поиск участка памяти большего размера, т.е. потом свойства верные для участка памяти который вы преобразовали и который имеет меньший размер будут распространены на участок памяти большего размера.

Если искать не для `EM->getTopLevelParent()`, а просто для `EM` он не находит?
И по идее должна быть проверка, что `RawDIMem` найден.

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      if (!dyn_cast<GlobalValue>(Ctx.V) && derivedType && Val->getType()->isPointerTy())
Я не понимаю этот `if`, т.е. соответствие `alias.tree.mapping` будет сохранено не для всех преобразованных переменных? Для части оно потеряется, это ведь приведет к потере части результатов анализа, чего не должно происходить. Что будет для `alloca` у них ведь тип не `DIDerivedType`? Для них не должно быть сохранено соответствие?

2021-04-17 16:32 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +      if (Ctx.L->contains(Call->getParent()) && Call->getParent() != Ctx.L->getExitingBlock()) {
Этой проверки вроде теперь не стало? Но, на всякий случай, отмечу:

- `ExitingBlock` - это блок внутри цикла, __из__ которого делается выход,
- `ExitBlock` - это блок вне цикл, __в__ который делается выход.

Т.е. в `ExitingBlock` вызовов быть не может, т.к. загрузка будет в `ExitBlock` уже после выхода из цикла.

2021-04-17 16:35 UTC, kaniandr commented on lib/Transform/IR/PointerReduction.cpp
> +                if (hasLoopLoad && hasLoopStore) {
Можно оставить, в этом есть какой-то смысл, т.к. наличие зависимости означает наличие записи. А если там не будет явных `store`, то значит будет косвенная запись и преобразовать не удастся.

Но можно делать `store` по адресу, а можно сохранять сам адрес. Стоит тогда проверять, что делается сохранение по адресу, т.е. в качестве какого операнда участвует объект.

2021-04-17 22:01 UTC, kaniandr reviewed
Посмотрел все. Основные замечания написал, где-то еще требуется рефакторинг стиля кода, об этом писать не стал.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +    &Ctx.L->getLoopPredecessor()->back());
В теории может не быть `Predecessor`, но если запускать проход после `LoopSimplifyPass`, то он всегда должен быть. Точнее всегда должен быть `Preheader`, а `Predecessor` несколько более слабое свойство, допускающей, что из базового блока будет переход не в цикл, а куда-то еще. Мне кажется, правильнее было бы вставлять в `Preheader`, т.к. из `Predecessor` можно попасть непонятно куда и пропустить обратную загрузку данных.

Стоит в `addAfterSROAAnalysis` подвинуть текущий проход ниже `LoopSimlifyPass, а в `runOnFunction` на всякий случай добавить проверку на наличие `Preheader` и если она не проходит, то не делать преобразование.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  if (Ctx.PhiLinks.find(BB) != Ctx.PhiLinks.end())
```suggestion
  if (Ctx.PhiLinks.count(BB))
```

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      auto *parentLink = Ctx.PhiLinks.find(BB->getSinglePredecessor())->second;
```suggestion
    if (auto Itr{Ctx.PhiLinks.find(BB->getSinglePredecessor())}; Itr != Ctx.PhiLinks.end()) {
      auto *parentLink = Itr->second;
```

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +struct ScalarizerContext {
Если внутренний класс, то должен быть в безымянном `namespace`, аналогично для других классов.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  DenseMap<BasicBlock *, phiNodeLink *> PhiLinks;
Лучше использовать `unique_ptr`, чтобы не думать об освобождении памяти:

```C++
DenseMap<BasicBlock *, std::unique_ptr<phiNodeLink>> PhiLinks;
```
Вообще хотелось бы избежать такого количества `new`. Ведь размер `PhiLinks` - фиксирован, в нем содержатся все блоки в цикле? Может быть просто заполнить `DenseMap`  блоками, а в качестве значения использовать не указатель а просто `phiNodeLink`, если `DenseMap` будет заполнено заранее, то ни итераторы, ни указатели на объекты уже не пострадают. Не понадобится делать `new` и `delete`.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  for (auto *Succ : successors(BB))
Здесь не должно быть проверки на то, что мы обрабатываем блоки только внутри нашего цикла?

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +    }
Я не понимаю, что здесь происходит и зачем.

Ищутся `store` но по какому-то странному шаблону, почему обязательно должно быть какое-то использование между `load` и `store`? Почему обязательно одно? Использование может быть в каком-то другом блоке, который еще не обрабатывался. А ниже, эти `store` удаляются.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +    if (SI && SI->getPointerOperand() == Ctx.V) {
А если `Ctx.ValueChanged == true`, тогда разве сохранение должно быть в `Ctx.V`?
По идее сохранение будет в какой-то `load` из `Ctx.V`, причем, где реально было этот `load` не совсем понятно.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        Phi->addIncoming(load, *Pred);
А когда возможна эта ситуация? Получается, что блок, через который попадаем в `Phi` не в цикле? Ведь вроде бы для всех блоков в цикле должны быть `LastValues`?

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  for (auto *Phi : Ctx.UniqueNodes) {
А не должно быть еще верхнего цикла, чтобы он крутился, пока хоть одну `Phi` можно убрать? Кажется, что если какая-то `Phi` удаляется, это может позволить потом еще какие-то удалить за счет `replaceAllUsesWith()`.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      Ctx.UniqueNodes.erase(Phi);
Какое-то подозрительное удаление из контейнера, по которому выполняется итерирование.

2021-04-17 22:01 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  if (pred_size(BB) == 1 && Ctx.ChangedLastInst.find(BB) == Ctx.ChangedLastInst.end())
Такое впечатление, что `ChangeLastInst` используется локально в данной функции, за исключением не понятного мне поиска внутри `ReplaceLoads`, вроде бы мы всегда работает с каждым блоком по отдельности? Точно ли нужен `map`, может достаточно просто локального флага для обрабатываемого в данный момент блока?

2021-04-17 22:01 UTC, kaniandr commented on lib/Core/Query.cpp
>        markIf<trait::Lock, trait::NoPromotedScalar>));
Похоже стоит опустить ниже (см. в комментариях к `PointerScalrizer.cpp`).

2021-04-17 22:01 UTC, kaniandr commented on include/tsar/Analysis/Memory/Passes.h
> +
```suggestion
```

2021-04-17 22:01 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> -#include "tsar/Analysis/Memory/DIDependencyAnalysis.h"
Порядок `#include` лучше не трогать, чтобы это не путало. Новых ведь не добавилось.

2021-04-17 22:01 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +      Loc.Var = DIOldVar;
Думаю так делать нельзя, т.к. "новая переменная" породила `Loc` у которой `DIExpressions` пуст, а вот какой должен быть `DIExpression`, чтобы соответствовать "старой переменной" это еще вопрос. Если замена была для

```C
void foo(int *X) {
 ...
}
```

То старая память была `*X`, после замены в `Loc` с сохранением пустого `DIExpression` получится просто `X`.
Мне кажется изменение `Loc` не нужно, оно ни на что не повлияет, и нет необходимости хранить в `alias.tree.mapping` старую переменную, достаточно вершины дерева и новой переменной. Тем более, что из вершины дерева можно вытащить переменную.

2021-04-17 22:01 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +bool handleLoopEmptyBindings(
Когда-то была такая переписка:

>Сейчас, чтобы работал анализ нужно. чтобы была закомментирована проверка наличия связанных не размещенных на регистрах переменных   `/*!DIMTraitItr->getMemory()->emptyBinding() ||*/` в updateTraits.
Это не безопасно, нужно добавить проверку, что если такие переменные есть т.е. если  emptyBinding==false, то они находятся вне цикла, т.е. что можно безопасно учитывать результаты анализа полученные для регистров. Фактически это что-то вроде упрощенной проверки, которую вы делаете, чтобы понять, можно ли размещать переменную на регистре для данного цикла. Т.е. можно взять связанные с DIMemory адреса Value (DIMemory::begin(), DIMemory::end()) и проверить, что они не используются в цикле. А также нужно проверить, что нет косвенного доступа к этой памяти в цикле, т.е. можно по дереву псевдонимов посмотреть пересекающиеся DIMemory и посмотреть для них отсутствие свойства trait::DirectAccess для текущего цикла. Мне кажется, что этого достаточно, но надо проверить как такая проверка будет работать.

В принципе, реализация здесь похожа на правду, но есть нюансы (см. ниже).

2021-04-17 22:01 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +        !DIAliasSTR.isEqual(PoolNode, MemNode))
Разрешать `isEqual` - это не правильно, так же как и в основном проходе. `isEqual` означает, что два участка памяти лежат в одной вершине дерева псевдонимов, т.е. если это разные участки памяти, то это как раз и будет косвенный доступ. Здесь можно разрешать, только если `Trait.getMemory() == Mem`.

Также здесь нужно проверять только те `Trait`, для которых есть `trait::DirectAccess` остальные переменные явным образом в цикле не используются и поэтому не должны влиять на анализ. Это должно немного расширить применимость анализа.

2021-04-17 22:01 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +    if (auto *CE = dyn_cast<ConstantExpr>(Loc))
Последовательность `ConstantExpr` может быть длиннее, т.е. нужно идти дальше по цепочке использований, пока не дойдете до всех конечных инструкций.

Например, как-то так:

```C++
     if (auto *CE = dyn_cast<ConstantExpr>(User)) {
        SmallVector<ConstantExpr *, 4> WorkList{ CE };
        do {
          auto *Expr = WorkList.pop_back_val();
          for (auto &ExprU : Expr->uses()) {
            auto ExprUse = ExprU.getUser();
            if (auto ExprUseInst = dyn_cast<Instruction>(ExprUse))
               ...
            else if (auto ExprUseExpr = dyn_cast<ConstantExpr>(ExprUse))
              WorkList.push_back(ExprUseExpr);
          }
        } while (!WorkList.empty());
     }
```

2021-04-18 20:07 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +        continue;
Убрал еще до этого, не закоммитил

2021-04-18 20:19 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +                if (hasLoopLoad && hasLoopStore) {
Добавил проверку на сохранение по адресу

2021-04-18 20:19 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +        T.unset<trait::NoPromotedScalar>();
Переделал, снимается только для тех участков, где было преобразование

2021-04-18 20:20 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +      if (Ctx.L->contains(Call->getParent()) && Call->getParent() != Ctx.L->getExitingBlock()) {
Да, не стало. Я в двух местах перепутал Exit и Exiting блоки

2021-04-18 20:21 UTC, v-makeev commented on lib/Transform/IR/PointerReduction.cpp
> +    if (Ctx.ValueChanged && Store && Ctx.L->contains(Store)) {
Добавил проверку на операнд `store`

2021-04-18 21:33 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +        Phi->addIncoming(load, *Pred);
Почему-то был уверен, что у меня возникала такая ситуация при нескольких вложенных циклах (после чего добавил эту ветку), но не смог сейчас воспроизвести

2021-04-18 21:33 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +        Phi->addIncoming(load, *Pred);
Уберу

2021-05-10 11:34 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +  DenseMap<BasicBlock *, phiNodeLink *> PhiLinks;
Переписал на значения вместо указателей

2021-05-10 11:34 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +        if (!STR.isEqual(EMNode, InstNode) && !STR.isUnreachable(EMNode, InstNode))
Поправил и добавил проверку на совпадение value в load  и store

2021-05-10 11:35 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +      }
Добавил

2021-05-10 11:35 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +      AT.getDomTree());
Проверил без `getTopLevelParent()`, все работает. Не знаю, зачем я добавил это

2021-05-10 11:36 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +      if (!dyn_cast<GlobalValue>(Ctx.V) && derivedType && Val->getType()->isPointerTy())
Добавил проверку на пустую отладочную информацию и сделал этот if для всех переменных

2021-05-10 11:38 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +    }
Переписал этот метод. Не знаю, зачем раньше бы поиск связанных load и store. Сейчас просто делается итерация по всем инструкциям в цикле, и если находится load V, то его использования заменяются, а если store V, то обновляется LastValues

2021-05-10 11:38 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +  if (pred_size(BB) == 1 && Ctx.ChangedLastInst.find(BB) == Ctx.ChangedLastInst.end())
Переписал метод и сделал булевский флаг

2021-05-16 07:31 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +    }
Мне сейчас пришло в голову, что это могло быть связано как раз с https://github.com/dvm-system/tsar/pull/5#discussion_r615294465

Брался `load`, который разыменование, и выполнялся поиск `store`, которые пишут в это `load`. Но реализация была явно странная, как будто рассчитанная на какой-то конкретный случай.

Может в `runOnFunction` добавить проверки, что `load` должен использоваться только внутри того блока, где он был сделан. И делать их как для `Ctx.ValueChanged == true` (для обоих последовательных `load`), так и для `false`. Мне кажется это не должно повлиять на область применимости алгоритма, т.к. другие ситуации вряд ли возникнут после преобразований в проходах LLVM, но мне кажется, их можно создать искусственно, поменяв LLVM IR руками.

2021-05-16 07:34 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      if (Ctx.LastValues.find(*Pred) != Ctx.LastValues.end())
А здесь когда-нибудь может не выполнится эта проверка? Мне кажется, что с точки зрения LLVM, если у блока есть предшественник, то в Phi-функции он должен быть упомянут. Т.е. есть подозрение, что если if не сработает, то будет некорректный LLVM IR. А если проверка выполняется всегда, то лучше тогда assert добавить вместо нее.

2021-05-16 07:42 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        Phi->addIncoming(load, *Pred);
Осталась проверка:
```C++
if (Ctx.LastValues.find(*Pred) != Ctx.LastValues.end()) {
```

Она ведь по идее всегда выполняется? Мне кажется, что с точки зрения LLVM, если у блока есть предшественник, то в Phi-функции он должен быть упомянут. Т.е. есть подозрение, что если if не сработает, то будет некорректный LLVM IR. А если проверка выполняется всегда, то лучше тогда assert добавить вместо нее.

2021-05-16 16:16 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        auto *instEM = AT.findUnknown(&I);
```suggestion
        auto *InstEM = AT.findUnknown(&I);
```

2021-05-16 16:20 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        if (!STR.isEqual(EMNode, InstNode) && !STR.isUnreachable(EMNode, InstNode))
`isEqual` остался в `unknownMemoryLambda`:

```C++
if (!STR.isEqual(instEM, EMNode) && !STR.isUnreachable(instEM, EMNode))
          HasWrite = true;
```
`isEqual` в принципе лишняя, т.к. `EMNode` - это `AliasEstimateNode`, а `instEM` - `AliasUnknownNode`.

2021-05-16 16:31 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        InsertedDI = createDbgInfo(Ctx, derivedType->getBaseType(), AT, MDsToAttach);
```suggestion
      auto *DerivedType = dyn_cast<DIDerivedType>(Ctx.DbgVar->getType());
      if (DerivedType && Val->getType()->isPointerTy())
        InsertedDI = createDbgInfo(Ctx, DerivedType->getBaseType(), AT, MDsToAttach);
```

2021-05-16 16:50 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      }
> И нет проверки DIExpression, а если там не пусто - это не вызовет проблем?

Такой проверки все еще нет? И мне кажется, это не правильно, т.к. регистр может описывать только часть переменной исходной программы, например, если он соответствует члену структуры и SROA разложил эту структуру на несколько регистров. В этом случае в `DIExpression` будет не пусто. Можно проверить, чтобы `getNumElements()` у `DIExpression` было `0`.

2021-05-16 17:23 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        LoopAttr.hasAttr(*L, Attribute::Returned))
О неточности этой проверки я писал в замечаниях к ВКР.

>Там должно быть AttrKind::AlwaysReturn (это атрибут SAPFOR, его нет в LLVM), Attribute::NoUnwind, Attribute::ReturnTwice - последние два - атрибуты LLVM и нужно проверять их отсутствие.
>Returned - ставится на параметры функции, а не на сами функции и на циклы он тоже не ставится. Он означает, что параметр является результатом функции.

2021-05-16 17:41 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +  return true;
Эта проверка ведь только для случая `Ctx.ValueChanged == true`, т.е. можно не делать цикл по `users()` в остальных случаях.

2021-05-16 18:38 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      if (derivedType && Val->getType()->isPointerTy())
По идее `Val->getType()->isPointerTy()` - всегда, иначе `Val` не был бы указателем на начало участка памяти.
Я правильно понимаю смысл проверки на `DIDerivedType`:
1. Если не `DIDerivedType` - то это `alloca` или `global`.
2. Если `DIDerivedType`  - то это, например `void foo(int *X) { *X = 100; }` при условии , что `X` пробросился и у нас остался только один `load` и мы хотим анализировать `*X` , на который и указывает ` Val`?

2021-05-16 18:39 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      handleLoads(Ctx, L->getLoopPredecessor(), Processed, true);
```suggestion
      insertPhiNodes(Ctx, L->getLoopPreheader(), true);
      DenseSet<BasicBlock *> Processed;
      handleLoads(Ctx, L->getLoopPreheader(), Processed, true);
```

2021-05-16 18:40 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +    auto storeVal = Ctx.ValueChanged ? Ctx.InsertedLoads.front() : Ctx.V;
```suggestion
    auto StoreVal = Ctx.ValueChanged ? Ctx.InsertedLoads.front() : Ctx.V;
```

2021-05-25 19:50 UTC, v-makeev commented on lib/Transform/IR/PointerScalarizer.cpp
> +      if (derivedType && Val->getType()->isPointerTy())
Насколько я понимаю, эта отладочная информация полностью совпадает с исходным кодом, поэтому derived type может быть и у `alloca`, и у `global` в том числе. И для `*int`, и для `int` надо создать копию типа `int`.
```
int sum(int *x, int n) {
  int *y;
  init(y);
  return (int) (x - y);
}

```
```
!16 = !DILocalVariable(name: "y", scope: !9, file: !1, line: 4, type: !12)
!14 = !DILocalVariable(name: "x", arg: 1, scope: !9, file: !1, line: 3, type: !12)
!12 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4, size: 64)
!4 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
```     
А `isPointerTy()` соответствует тэгу `DW_TAG_pointer_type`, поэтому его не будет для, например, обычного инта, от которого взяли адрес

2021-05-26 07:51 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +      if (derivedType && Val->getType()->isPointerTy())
Если у нас случай `int *y;`, то это уже двойной `load`, если `alloca` не была проброшена. А если она была проброшена, то `Val` - это уже не `alloca`.

> А isPointerTy() соответствует тэгу DW_TAG_pointer_type, поэтому его не будет для, например, обычного инта, от которого взяли адрес

Не совсем, тип в llvm и тип в отладочной информации могут не совпадать. Потому что, если это например `alloca`, то в llvm у нее тип всегда указатель, иначе нельзя делать `store` и `load`, а вот в отладочной информации будет тип уже той переменной, с которой эта `alloca` связана. Ведь `alloca` - это указатель на память выделенную под переменную на стеке, а не сама эта память, сама `alloca` - это регистр типа указателя. Тоже самое и про глобальные переменные.

`Val` не может быть не указателем, иначе бы в него не было `store`/`load`.

2021-06-01 11:20 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        continue;
- Глобальные переменные нужно обрабатывать также как и `alloca`.
- `Loc` может и не быть, например, для глобальных переменных ее нет.

Соответствующим образом надо поправить `createDbgInfo`, иначе сейчас глобальные переменные не преобразуются.

```suggestion
      if (isa<AllocaInst>(Ctx.V) || isa<GlobalVariable>(Ctx.V)) {
        DIM = findMetadata(Ctx.V, DILocs);
      }else {
        bool HasDbgInLoop = false;
        for (auto *BB : L->getBlocks())
          for (auto &I : BB->getInstList())
            if (auto *DVI = dyn_cast<DbgValueInst>(&I))
              if (DVI->getValue() == Ctx.V) {
                HasDbgInLoop = true;
                break;
              }
        if (!HasDbgInLoop)
          DIM = findMetadata(Ctx.V, {&L->getHeader()->front()}, AT.getDomTree(), DILocs);
      }
      if (!DIM || !DIM->isValid())
        continue;
```

2021-06-01 11:21 UTC, kaniandr commented on lib/Transform/IR/PointerScalarizer.cpp
> +        continue;
Не проходит `8` тестов из `tests/analysis/da_di`.

2021-06-05 10:34 UTC, kaniandr commented
По поводу `redundant` участков памяти.

Нужно дополнить метод `analyzeNode` в `DIDependenceAnalysis.cpp` в строке `1805`. В нем проверяется, что участок памяти перестал использоваться в цикле в трех местах, помеченных `LLVM_DEBUG(dbgs() << "[DA DI]: mark as redundant\n");`. Нужно проверить, что для участка памяти, который проверяется на `redundant` нет записи в `alias.tree.mapping` и если такая запись есть, то нужно проверить, что соответствующий регистр не используется в текущем цикле. Т.к. в `analyzeNode`  сейчас не передается анализируемый цикл, то придется добавить дополнительный параметр.

Проверка может выглядеть примерно так:

```C++
          bool IsAccessed{false};
          auto *F{L->getHeader()->getParent()}; // L - придется добавить как параметр к `analyzeNode`
          if (auto MD{F->getMetadata("alias.tree.mapping")}) {
            for (auto &Op : MD->operands()) {
              auto *DIN{dyn_cast<MDNode>(Op)};
              if (!DIN)
                continue;
              assert(DIN->getNumOperands() == 2 &&
                     "Alias tree mapping node must contain three elements");
              auto MappingMD{dyn_cast<MDNode>(DIN->getOperand(0))};
              if (MappingMD == M.getAsMDNode()) {  // M - это как раз тот участок памяти, для которого обновляем свойства, по ним идет основной цикл в `analyzeNode`
                auto *DINewVar{dyn_cast<DIVariable>(DIN->getOperand(1))};
                //Если нашли отображение, то нужно проверить, что регистр используется внутри цикла `L`, и если да, то `redundant` ставить нельзя.
                IsAccessed = true;
              }
            }
          }
```

2021-06-05 10:38 UTC, kaniandr commented
Анализ по регистрам делается не только для редукционных и индуктивных переменных, но и для приватных переменных (метод `analyzePrivatePromoted`). В нем тоже нужно сделать сопоставление с `alias.tree.mapping` через `mdNodeFromAliasTreeMapping` по аналогии с редукционными переменными. Нужно добавить аналогичную проверку:

```C++
  auto MD{mdNodeFromAliasTreeMapping(L->getHeader()->getParent(), Candidate)};
    if (!MD)
      auto *MD =
          getRawDIMemoryIfExists(L->getHeader()->getContext(), Candidate);
```

в начало цикла, в котором обновляются свойства:

```C++
 for (auto &Candidate : Privates) {
    if (OutwardUses.count(Candidate))
      continue;
```

2021-06-05 10:46 UTC, kaniandr commented
Есть проблема с тестом `dependence_2`:

```C++
double A[100];
int X;

void foo(int Flag) {
  for (int I = 0; I < 100; ++I) {
    // LLVM merge two if-stmt and implicitly transform it to
    // if (Flag) { ... } else { ... }
    // This allow us to perform analysis.
    if (Flag)
      X = A[I];
   A[I] = A[I] + 1;
   if (Flag)
     A[I+1] = X;
  }
}

```

Кусок с `if` и присваиванием в `X` был до преобразования такой:

```llvm
if.then:                                          ; preds = %for.body
  %conv = fptosi double %0 to i32, !dbg !51
  store i32 %conv, i32* @X, align 4, !dbg !52, !tbaa !53   ; присваивание X = A[I]
  %idxprom1 = zext i32 %I.0 to i64, !dbg !55
  %arrayidx2 = getelementptr inbounds [100 x double], [100 x double]* @A, i64 0, i64 %idxprom1, !dbg !55
  %1 = load double, double* %arrayidx2, align 8, !dbg !55, !tbaa !46
  %add = fadd double %1, 1.000000e+00, !dbg !56
  store double %add, double* %arrayidx2, align 8, !dbg !57, !tbaa !46
  %conv7 = sitofp i32 %conv to double, !dbg !58
  %add8 = add nuw nsw i32 %I.0, 1, !dbg !60
  %idxprom9 = zext i32 %add8 to i64, !dbg !61
  %arrayidx10 = getelementptr inbounds [100 x double], [100 x double]* @A, i64 0, i64 %idxprom9, !dbg !61
  store double %conv7, double* %arrayidx10, align 8, !dbg !62, !tbaa !46
  br label %for.inc, !dbg !61
```
после преобразования, информация о присваивании `X=A[I]` теряется, т.к. не добавляется соответствующая `llvm.dbg.value` для `%conv`.

```llvm
if.then:                                          ; preds = %for.body
  %conv = fptosi double %0 to i32, !dbg !55 ; нет dbg.value для связи с X
  %idxprom1 = zext i32 %I.0 to i64, !dbg !56
  %arrayidx2 = getelementptr inbounds [100 x double], [100 x double]* @A, i64 0, i64 %idxprom1, !dbg !56
  %1 = load double, double* %arrayidx2, align 8, !dbg !56, !tbaa !50
  %add = fadd double %1, 1.000000e+00, !dbg !57
  store double %add, double* %arrayidx2, align 8, !dbg !58, !tbaa !50
  %conv7 = sitofp i32 %conv to double, !dbg !59
  %add8 = add nuw nsw i32 %I.0, 1, !dbg !61
  %idxprom9 = zext i32 %add8 to i64, !dbg !62
  %arrayidx10 = getelementptr inbounds [100 x double], [100 x double]* @A, i64 0, i64 %idxprom9, !dbg !62
  store double %conv7, double* %arrayidx10, align 8, !dbg !63, !tbaa !50
  br label %for.inc, !dbg !62
```

Также есть еще один неприятный момент, который происходит из-за того, что `X` загружается перед циклом и в цикл добавляются `Phi` - функции, которые его используют. Фактически эти функции используют сами себя в духе `X = X`, но это не даст проанализировать `X` как приватную, т.к. есть использования через `Phi` функции с предыдущей итерации. Можно ли как-то не добавлять эти функции в таком случае❓  Или если это сложно сделать, то видимо придется что-то дополнительно делать в анализе, чтобы исключать обращения в виде `X = X` из анализа.

2021-06-05 17:58 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +    }
Здесь похоже не совсем та проверка. Ведь речь шла о том, что связанные `Value` с участком памяти не должны использоваться внутри цикла, т.е. не должно быть инструкций, в которых они являются операндами в цикле. А здесь проверка на то, что сами эти `Value` - являются инструкциями. Из-за этого часть тестов не проходит, например, `address_3`. Там привязанное значение - это глобальная переменная `@X`, она используется в цикле, но из-за того, что эта проверка не находит это использование для `X` снимается свойство `address access`, что не правильно.

2021-06-06 09:25 UTC, kaniandr commented
По поводу этого комментария:

> [после преобразования, информация о присваивании X=A[I] теряется, т.к. не добавляется соответствующая llvm.dbg.value для %conv](https://github.com/dvm-system/tsar/pull/5#issuecomment-855220900)

Мне кажется для `Phi` вершин вообще не надо добавлять `llvm.dbg.value`, т.к. `llvm.dbg.value` SAPFOR интерпретирует как присваивание в переменную в этой точке, а в точка с `Phi` этих присваиваний ведь не было. Зато нужно вместо всех удаленных `store` добавить `dbg.value` привязав их к тому регистру, который сохранялся в этот удаленный `store`. Для `load` перед циклом `dbg.value` нужно оставить. Тогда по идее все анализы должны работать как раньше.

2021-06-14 19:11 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +    }
Здесь что-то странное было со вложенностью `if` в цикл и в друг друга.

```suggestion
    for (auto *User : Loc->users()) {
      if (auto *I = dyn_cast<Instruction>(User)) {
        if (L->contains(I))
          return false;
      } else if (auto *CE = dyn_cast<ConstantExpr>(User)) {
        SmallVector<ConstantExpr *, 4> WorkList{CE};
        do {
          auto *Expr = WorkList.pop_back_val();
          for (auto &ExprU : Expr->uses()) {
            auto ExprUse = ExprU.getUser();
            if (auto ExprUseInst = dyn_cast<Instruction>(ExprUse)) {
              if (L->contains(ExprUseInst))
                return false;
            } else if (auto ExprUseExpr = dyn_cast<ConstantExpr>(ExprUse)) {
              WorkList.push_back(ExprUseExpr);
            }
          }
        } while (!WorkList.empty());
      }
    }
```

2021-06-14 19:15 UTC, kaniandr commented on lib/Analysis/Memory/DIDependenceAnalysis.cpp
> +          }
Странная проверка. Проверяется, что для участка памяти который был размещен на регистрах в цикле будут инструкции с ним связанные. Ведь если участок памяти попал на регистр, то в цикле таких инструкций не может быть в принципе, т.е. `UsedInLoop` всегда `false`. Нужно эту проверку делать для переменной из `alias.tree.mapping`. Т.е. если для `M` есть запись в `alias.tree.mapping`, то нужно взять добавленную в проходе переменную, и посмотреть есть ли для нее `llvm.dbg.value` внутри цикла.

2022-04-26 23:25 UTC, kaniandr commented
Pull request интегрирован в основную ветвь репозитория, после исправлений и тестирования, основные коммиты:

[TSAR, IR, Ptr2Reg] Initial implementation of pointer promotion.
[TSAR, IR, Ptr2Reg] Major update of ptr2reg pass and dependence analysis pass.

2022-04-26 23:25 UTC, closed without merging